<x-marketing-layout title="Features" description="Explore every MuebleDesk feature for invoicing, payments, recurring billing, expenses, customer access and Malaysian e-Invoice operations.">
<main><section class="bg-gradient-to-br from-indigo-600 via-violet-600 to-fuchsia-600 text-white"><div class="mx-auto max-w-7xl px-4 py-20 sm:px-6 lg:px-8"><p class="text-sm font-black uppercase tracking-[.2em] text-indigo-200">Detailed product capabilities</p><h1 class="mt-4 max-w-4xl text-4xl font-black tracking-tight sm:text-6xl">Every tool your company needs to move from opportunity to paid, recorded and compliant.</h1><p class="mt-6 max-w-3xl text-lg leading-8 text-indigo-100">MuebleDesk is not only an invoice generator. It is a company workspace, customer portal, billing engine, operational ledger and Malaysian e-Invoice workflow.</p></div></section>
<section class="mx-auto max-w-7xl px-4 py-20 sm:px-6 lg:px-8"><div class="space-y-16">@foreach([
['Sales operations','from-indigo-500 to-cyan-500',[['Client records','Maintain contact people, billing email, phone, addresses, website, identity type, identification number, TIN and SST registration details.'],['Professional quotations','Create itemised quotations, calculate totals, export PDF documents and convert approved quotations into invoices.'],['Invoice lifecycle','Draft, issue, update and download invoices while monitoring payment status, balance and due dates.'],['Search and exports','Search business records quickly and export clients, quotations, invoices, payments, expenses and recurring schedules.']]],
['Payments and collections','from-fuchsia-500 to-rose-500',[['Manual payment recording','Record bank transfers, cash, cheque or other payment methods against an invoice.'],['Online payment support','Generate supported online payment experiences and process webhook updates from configured gateways.'],['Receipts and audit history','Provide downloadable receipts and retain payment references and timestamps.'],['Outstanding balance visibility','See what has been paid, what remains due and which invoices need attention.']]],
['Recurring revenue','from-amber-400 to-orange-500',[['Recurring invoice schedules','Create recurring invoices from existing documents and define repeat billing behaviour.'],['Activation controls','Pause or reactivate schedules without deleting historical records.'],['Subscription-plan billing','Offer fixed-duration SaaS plans with configurable role limits and automatic renewal preferences.'],['Renewal monitoring','Track renewal attempts, failures, expiry and subscription status.']]],
['Malaysian e-Invoice','from-emerald-500 to-teal-500',[['Customer identity readiness','Capture the tax and identity data required for MyInvois workflows.'],['Submission control','Submit eligible invoices with throttling and validation safeguards.'],['Status reconciliation','Refresh status, inspect invalid or rejected results and avoid blind duplicate retries.'],['Validated document access','Expose the final status, document link and QR when MyInvois validation succeeds.']]],
['Finance and management','from-cyan-500 to-blue-600',[['Expense records','Record operating expenses with dates, categories, descriptions and amounts.'],['Profit and loss','Review business income against spending for a clearer operational picture.'],['Dashboard metrics','See revenue, outstanding balances, recent activity and critical workflow status.'],['Activity logs','Keep an administrative history of important changes for accountability.']]],
['Access, SaaS and governance','from-slate-700 to-slate-950',[['Company-isolated workspaces','Each company operates in a tenant context so its data stays separated.'],['Role-based controls','Differentiate superadmin, company administrator, employee and customer capabilities.'],['Customer portal','Allow customers to view and download their invoices and manage eligible e-Invoice steps.'],['Platform administration','Manage companies, users, plans, subscriptions, payment history and platform settings.'],['Security controls','Email verification, optional two-factor authentication, encrypted settings and API-key management.'],['Plan limits','Control admin, employee and client allowances independently per subscription plan.']]]
] as $group)<section><div class="flex items-center gap-4"><span class="h-12 w-2 rounded-full bg-gradient-to-b {{ $group[1] }}"></span><h2 class="text-3xl font-black tracking-tight">{{ $group[0] }}</h2></div><div class="mt-8 grid gap-5 md:grid-cols-2">@foreach($group[2] as $feature)<article class="rounded-[2rem] border border-slate-200 bg-white p-7 shadow-sm"><h3 class="text-xl font-black">{{ $feature[0] }}</h3><p class="mt-3 text-sm leading-7 text-slate-600">{{ $feature[1] }}</p></article>@endforeach</div></section>@endforeach</div></section>
<section class="bg-slate-950 px-4 py-20 text-white"><div class="mx-auto max-w-5xl text-center"><h2 class="text-3xl font-black sm:text-5xl">Built to connect the entire billing workflow.</h2><p class="mx-auto mt-5 max-w-2xl text-slate-400">Create a verified account, launch your company, choose a plan and begin operating from one secure workspace.</p><a href="{{ route('register') }}" class="mt-8 inline-flex rounded-2xl bg-white px-6 py-4 text-sm font-black text-slate-950">Start using MuebleDesk</a></div></section></main>
</x-marketing-layout>