<x-marketing-layout title="Features" description="Explore MuebleDesk features for customer management, quotations, invoicing, payments, recurring billing, expenses and Malaysian e-Invoices.">
<main><section class="bg-gradient-to-br from-indigo-600 via-violet-600 to-fuchsia-600 text-white"><div class="mx-auto max-w-7xl px-4 py-20 sm:px-6 lg:px-8"><p class="text-sm font-black uppercase tracking-[.2em] text-indigo-200">Everything in one place</p><h1 class="mt-4 max-w-4xl text-4xl font-black tracking-tight sm:text-6xl">The tools your business needs to quote, invoice, collect and stay organised.</h1><p class="mt-6 max-w-3xl text-lg leading-8 text-indigo-100">MuebleDesk brings your customer records, sales documents, payments, recurring billing, expenses and Malaysian e-Invoices into one easy-to-manage workspace.</p></div></section>
<section class="mx-auto max-w-7xl px-4 py-20 sm:px-6 lg:px-8"><div class="space-y-16">@foreach([
['Customers and sales','from-indigo-500 to-cyan-500',[['Customer records','Keep contact details, billing information, addresses and tax information in one organised profile.'],['Professional quotations','Create itemised quotations, calculate totals, export PDFs and turn approved quotations into invoices.'],['Complete invoicing','Create, issue, update and download invoices while monitoring payment status, balances and due dates.'],['Fast search and exports','Find records quickly and export your customer, quotation, invoice, payment and expense information when needed.']]],
['Payments and collections','from-fuchsia-500 to-rose-500',[['Record every payment','Add bank transfers, cash, cheque and other payment methods directly to the related invoice.'],['Online payment options','Offer convenient online payment experiences when supported payment methods are enabled.'],['Receipts and payment history','Provide downloadable receipts and keep references, dates and payment details together.'],['Outstanding balance tracking','See what has been paid, what remains due and which invoices need follow-up.']]],
['Recurring income','from-amber-400 to-orange-500',[['Recurring invoices','Set up repeat invoices for retainers, memberships and ongoing services.'],['Pause when needed','Temporarily stop or restart a recurring schedule without losing previous records.'],['Flexible business plans','Choose a plan that matches the size of your team and customer base.'],['Renewal visibility','Keep track of renewal dates, payment issues and subscription status.']]],
['Malaysian e-Invoice','from-emerald-500 to-teal-500',[['Tax-ready customer details','Store the identity and tax information needed for e-Invoice preparation.'],['Guided submission','Submit eligible invoices with checks that help reduce avoidable errors.'],['Status tracking','Review validation progress and understand when action is required.'],['Validated document access','Access final validation details and available document links once approved.']]],
['Finance and reporting','from-cyan-500 to-blue-600',[['Expense tracking','Record operating expenses with dates, categories, descriptions and amounts.'],['Profit and loss','Compare income against expenses for a clearer view of business performance.'],['Dashboard insights','See revenue, outstanding balances, recent activity and important updates at a glance.'],['Change history','Review important account and business changes when you need additional clarity.']]],
['Access and account control','from-slate-700 to-slate-950',[['Dedicated business workspace','Keep your company records separate and organised in one place.'],['Team permissions','Give owners, employees and customers access based on what they need to do.'],['Customer access','Let customers securely view and download assigned invoices and related information.'],['Account security','Use email verification, two-factor authentication and secure account controls.'],['API access','Create and manage API keys for approved integrations.'],['Plan allowances','Choose user and customer limits that fit your business size.']]]
] as $group)<section><div class="flex items-center gap-4"><span class="h-12 w-2 rounded-full bg-gradient-to-b {{ $group[1] }}"></span><h2 class="text-3xl font-black tracking-tight">{{ $group[0] }}</h2></div><div class="mt-8 grid gap-5 md:grid-cols-2">@foreach($group[2] as $feature)<article class="rounded-[2rem] border border-slate-200 bg-white p-7 shadow-sm"><h3 class="text-xl font-black">{{ $feature[0] }}</h3><p class="mt-3 text-sm leading-7 text-slate-600">{{ $feature[1] }}</p></article>@endforeach</div></section>@endforeach</div></section>
<section class="bg-slate-950 px-4 py-20 text-white"><div class="mx-auto max-w-5xl text-center"><h2 class="text-3xl font-black sm:text-5xl">Bring your billing workflow together.</h2><p class="mx-auto mt-5 max-w-2xl text-slate-400">Create your account, add your company details and begin managing customers, invoices and payments in one place.</p><a href="{{ route('register') }}" class="mt-8 inline-flex rounded-2xl bg-white px-6 py-4 text-sm font-black text-slate-950">Get started</a></div></section></main>
</x-marketing-layout>