<x-marketing-layout title="Complete SaaS invoicing platform">
<main>
<section class="relative overflow-hidden bg-slate-950 text-white">
    <div class="absolute inset-0 bg-[radial-gradient(circle_at_20%_20%,rgba(99,102,241,.35),transparent_32%),radial-gradient(circle_at_80%_30%,rgba(217,70,239,.25),transparent_30%),radial-gradient(circle_at_50%_90%,rgba(34,211,238,.2),transparent_35%)]"></div>
    <div class="relative mx-auto grid max-w-7xl gap-12 px-4 py-20 sm:px-6 lg:grid-cols-[1.05fr_.95fr] lg:px-8 lg:py-28">
        <div><span class="inline-flex rounded-full border border-white/15 bg-white/10 px-4 py-2 text-xs font-black uppercase tracking-[.18em] text-indigo-200">From company setup to paid invoice</span><h1 class="mt-7 text-4xl font-black leading-tight tracking-tight sm:text-6xl">Run invoicing, payments and e-Invoices from one <span class="bg-gradient-to-r from-cyan-300 via-indigo-300 to-fuchsia-300 bg-clip-text text-transparent">business command center.</span></h1><p class="mt-6 max-w-2xl text-lg leading-8 text-slate-300">MuebleDesk gives each company its own secure workspace to manage clients, quotations, invoices, recurring billing, payments, expenses, profit and loss, customer access and Malaysian MyInvois submissions.</p><div class="mt-8 flex flex-col gap-3 sm:flex-row"><a href="{{ route('register') }}" class="rounded-2xl bg-white px-6 py-4 text-center text-sm font-black text-slate-950 shadow-xl">Create your account</a><a href="{{ route('marketing.features') }}" class="rounded-2xl border border-white/20 bg-white/10 px-6 py-4 text-center text-sm font-black">Explore every feature</a></div><div class="mt-8 flex flex-wrap gap-5 text-sm font-bold text-slate-400"><span>✓ Company-isolated data</span><span>✓ Role-based access</span><span>✓ Stripe-ready billing</span><span>✓ MyInvois workflow</span></div></div>
        <div class="relative"><div class="rounded-[2rem] border border-white/10 bg-white/10 p-4 shadow-2xl backdrop-blur"><div class="rounded-[1.5rem] bg-white p-5 text-slate-900"><div class="flex items-center justify-between"><div><p class="text-xs font-bold uppercase tracking-wider text-slate-400">Business overview</p><h2 class="mt-1 text-xl font-black">August performance</h2></div><span class="rounded-full bg-emerald-50 px-3 py-1 text-xs font-black text-emerald-700">Healthy</span></div><div class="mt-5 grid grid-cols-2 gap-3"><div class="rounded-2xl bg-indigo-50 p-4"><p class="text-xs font-bold text-indigo-500">Revenue</p><p class="mt-2 text-2xl font-black">RM 48,920</p></div><div class="rounded-2xl bg-fuchsia-50 p-4"><p class="text-xs font-bold text-fuchsia-500">Outstanding</p><p class="mt-2 text-2xl font-black">RM 9,450</p></div><div class="rounded-2xl bg-cyan-50 p-4"><p class="text-xs font-bold text-cyan-600">Valid e-Invoices</p><p class="mt-2 text-2xl font-black">128</p></div><div class="rounded-2xl bg-amber-50 p-4"><p class="text-xs font-bold text-amber-600">Expenses</p><p class="mt-2 text-2xl font-black">RM 16,280</p></div></div><div class="mt-4 rounded-2xl bg-slate-950 p-5 text-white"><p class="text-xs font-bold uppercase tracking-wider text-slate-400">Workflow</p><div class="mt-4 grid grid-cols-4 gap-2 text-center text-xs font-black"><span class="rounded-xl bg-indigo-500 p-3">Quote</span><span class="rounded-xl bg-violet-500 p-3">Invoice</span><span class="rounded-xl bg-fuchsia-500 p-3">Paid</span><span class="rounded-xl bg-emerald-500 p-3">MyInvois</span></div></div></div></div></div>
    </div>
</section>

<section class="mx-auto max-w-7xl px-4 py-20 sm:px-6 lg:px-8"><div class="max-w-3xl"><p class="text-sm font-black uppercase tracking-[.18em] text-indigo-600">What MuebleDesk actually replaces</p><h2 class="mt-3 text-3xl font-black tracking-tight sm:text-5xl">Stop stitching together spreadsheets, PDFs, payment links and government portals.</h2><p class="mt-5 text-lg leading-8 text-slate-600">The platform connects the entire order-to-cash process, while keeping operational data isolated by company and accessible only to the right roles.</p></div><div class="mt-12 grid gap-5 md:grid-cols-2 lg:grid-cols-3">@foreach([
['🧑‍💼','Clients & identities','Store contact, billing and tax details, portal access, TIN information and transaction history in one record.'],['📝','Quotations','Prepare professional quotations, export PDFs and convert approved quotations into invoices without re-entering data.'],['🧾','Invoices','Create itemised invoices, manage status, download branded PDFs and monitor balances and due dates.'],['💳','Payments','Record manual payments, accept supported online payments, generate receipts and maintain an auditable payment history.'],['🔁','Recurring billing','Turn invoices into recurring schedules for retainers, subscriptions and repeat services.'],['🇲🇾','Malaysian e-Invoice','Validate customer identity data, submit eligible invoices to MyInvois, track status and access final validated documents and QR links.'],['💸','Expenses & P&L','Capture operating expenses, categorise spending and review revenue against costs in profit-and-loss reporting.'],['🔐','Roles & customer access','Separate administrator, employee and customer capabilities, with company-level plan limits and optional two-factor authentication.'],['🏢','SaaS company workspaces','Each registered organisation gets an isolated workspace and subscription controlled from a central client portal.']
] as $f)<article class="rounded-[2rem] border border-slate-200 bg-white p-6 shadow-sm transition hover:-translate-y-1 hover:shadow-xl"><div class="text-3xl">{{ $f[0] }}</div><h3 class="mt-5 text-xl font-black">{{ $f[1] }}</h3><p class="mt-3 text-sm leading-7 text-slate-600">{{ $f[2] }}</p></article>@endforeach</div></section>

<section class="bg-gradient-to-br from-indigo-50 via-white to-fuchsia-50"><div class="mx-auto max-w-7xl px-4 py-20 sm:px-6 lg:px-8"><div class="grid gap-10 lg:grid-cols-2 lg:items-center"><div><p class="text-sm font-black uppercase tracking-[.18em] text-fuchsia-600">Built around real work</p><h2 class="mt-3 text-3xl font-black sm:text-5xl">A guided flow from first customer to compliant record.</h2><div class="mt-8 space-y-5">@foreach([['1','Create your company','Register, verify your email, enter company details and choose a plan.'],['2','Prepare the sale','Create the client, issue a quotation and convert it to an invoice.'],['3','Collect and reconcile','Accept or record payment, issue receipts and update invoice balances.'],['4','Complete e-Invoice processing','Submit eligible paid invoices to MyInvois and monitor validation.']] as $s)<div class="flex gap-4"><span class="flex h-11 w-11 shrink-0 items-center justify-center rounded-2xl bg-slate-950 font-black text-white">{{ $s[0] }}</span><div><h3 class="font-black">{{ $s[1] }}</h3><p class="mt-1 text-sm leading-6 text-slate-600">{{ $s[2] }}</p></div></div>@endforeach</div></div><div class="grid gap-4 sm:grid-cols-2"><div class="rounded-[2rem] bg-indigo-600 p-7 text-white"><p class="text-sm font-bold text-indigo-200">For owners</p><p class="mt-3 text-2xl font-black">Visibility across money, teams and compliance.</p></div><div class="rounded-[2rem] bg-fuchsia-500 p-7 text-white sm:mt-10"><p class="text-sm font-bold text-fuchsia-100">For staff</p><p class="mt-3 text-2xl font-black">A clear workflow for daily sales and finance operations.</p></div><div class="rounded-[2rem] bg-cyan-500 p-7 text-white"><p class="text-sm font-bold text-cyan-100">For customers</p><p class="mt-3 text-2xl font-black">Secure access to invoices, PDFs and e-Invoice actions.</p></div><div class="rounded-[2rem] bg-slate-950 p-7 text-white sm:mt-10"><p class="text-sm font-bold text-slate-400">For platform teams</p><p class="mt-3 text-2xl font-black">Plans, subscriptions, payments and company governance.</p></div></div></div></div></section>

<section class="mx-auto max-w-7xl px-4 py-20 sm:px-6 lg:px-8"><div class="rounded-[2.5rem] bg-gradient-to-r from-indigo-600 via-violet-600 to-fuchsia-600 px-6 py-12 text-center text-white sm:px-12"><h2 class="text-3xl font-black sm:text-5xl">Give your business one reliable system of record.</h2><p class="mx-auto mt-5 max-w-2xl text-base leading-7 text-indigo-100">Start with a verified client account, create your company workspace and manage the full billing lifecycle in one platform.</p><div class="mt-8 flex flex-col justify-center gap-3 sm:flex-row"><a href="{{ route('register') }}" class="rounded-2xl bg-white px-6 py-4 text-sm font-black text-slate-950">Create account</a><a href="{{ route('marketing.contact') }}" class="rounded-2xl border border-white/25 bg-white/10 px-6 py-4 text-sm font-black">Talk to us</a></div></div></section>
</main>
</x-marketing-layout>