@php
    $documentTemplate = $settings['invoice_template'] ?? 'modern';
    $clientAddress = $invoice->client->billing_address ?: 'Address not provided';
    $clientEmail = $invoice->client->billing_email ?: $invoice->client->email;
    $paymentGatewayLabel = str_contains((string) $invoice->payment_link, 'stripe.com') ? 'Stripe Checkout' : 'Secure online payment';
@endphp
<!DOCTYPE html><html><head><meta charset="utf-8"><title>Invoice {{ $invoice->invoice_number }}</title>@include('pdfs.partials.styles')</head><body class="template-{{ $documentTemplate }}">
@php($documentTitle = 'INVOICE') @php($documentNumber = $invoice->invoice_number) @include('pdfs.partials.header')
<table class="info"><tr><td><div class="label">BILLED TO</div><strong>{{ $invoice->client->name }}</strong><br>{!! nl2br(e($clientAddress)) !!}<br>{{ $clientEmail }} · {{ $invoice->client->phone ?: 'No phone' }}<br><strong>TIN:</strong> {{ $invoice->client->tin_number ?: 'Not provided' }}<br><strong>{{ $invoice->client->id_type ?: 'ID' }}:</strong> {{ $invoice->client->id_number ?: 'Not provided' }}<br><strong>SST:</strong> {{ $invoice->client->sst_registration_number ?: 'Not registered' }}</td><td><div class="label">DOCUMENT DETAILS</div><strong>Issue:</strong> {{ $invoice->date->format('d M Y') }}<br><strong>Due:</strong> {{ $invoice->due_date->format('d M Y') }}<br><strong>Currency:</strong> {{ $settings['currency'] ?? 'MYR' }}<br><span class="badge {{ $invoice->payment_state === 'Paid' ? 'paid' : ($invoice->payment_state === 'Partially Paid' ? 'partial' : 'unpaid') }}">{{ strtoupper($invoice->payment_state) }}</span></td></tr></table>
<table class="items"><thead><tr><th>#</th><th>Item / Description</th><th class="num">Qty</th><th class="num">Unit Price</th><th class="num">Amount</th></tr></thead><tbody>@foreach($invoice->items as $item)<tr><td>{{ $loop->iteration }}</td><td><strong>{{ $item->item_name }}</strong>@if($item->description)<div class="muted document-rich-text">{!! $item->description !!}</div>@endif</td><td class="num">{{ $item->quantity }}</td><td class="num">RM {{ number_format($item->price, 2) }}</td><td class="num">RM {{ number_format($item->total, 2) }}</td></tr>@endforeach</tbody></table>
<table class="summary"><tr><td>Subtotal</td><td>RM {{ number_format($invoice->sub_total, 2) }}</td></tr><tr><td>Discount{{ $invoice->discount_type === 'percentage' ? ' ('.number_format($invoice->discount_value, 2).'%)' : '' }}</td><td>- RM {{ number_format($invoice->discount_amount, 2) }}</td></tr><tr><td>{{ Str::title(str_replace('_',' ', $invoice->tax_type ?: 'No tax')) }} ({{ number_format($invoice->tax_rate, 2) }}%)</td><td>RM {{ number_format($invoice->tax_amount, 2) }}</td></tr><tr class="grand"><td>Grand Total</td><td>RM {{ number_format($invoice->total_amount, 2) }}</td></tr><tr><td>Paid</td><td>RM {{ number_format($invoice->amount_paid, 2) }}</td></tr><tr><td>Balance Due</td><td>RM {{ number_format(max(0, $invoice->total_amount-$invoice->amount_paid), 2) }}</td></tr></table><div class="clear"></div>
@if($invoice->payment_link && $invoice->payment_state !== 'Paid')<div class="payment"><div class="payment-copy"><strong>PAY SECURELY ONLINE</strong><br><span class="muted">Use {{ $paymentGatewayLabel }} to pay the outstanding balance.</span></div><a class="payment-button" href="{{ $invoice->payment_link }}">Pay Invoice Online</a><div class="payment-fallback"><span class="muted">If the button does not open, copy this link:</span><br><a href="{{ $invoice->payment_link }}">{{ $invoice->payment_link }}</a></div></div>@endif
<div class="two"><div><div class="label">PAYMENT TERMS</div><p>{!! nl2br(e($settings['payment_terms'] ?? 'Payment is due by the stated due date.')) !!}</p></div><div><div class="label">E-INVOICE READY FIELDS</div><p>Document type: Invoice<br>Supplier registration: {{ $settings['company_registration_number'] ?? '—' }}<br>Supplier tax ID: {{ $settings['tax_registration_number'] ?? '—' }}<br>Buyer TIN: {{ $invoice->client->tin_number ?: '—' }}<br>Buyer ID: {{ $invoice->client->id_type ?: '—' }} {{ $invoice->client->id_number ?: '' }}<br>Tax category: {{ $invoice->tax_type ?: 'none' }}</p></div></div>
<div class="footer">{!! nl2br(e($settings['invoice_footer_note'] ?? 'Thank you for your business.')) !!}<br><span>Generated electronically · {{ now()->format('d M Y H:i') }}</span></div>
</body></html>