@php
    $documentTemplate = $settings['quotation_template'] ?? 'modern';
    $clientAddress = $quotation->client->billing_address ?: 'Address not provided';
    $clientEmail = $quotation->client->billing_email ?: $quotation->client->email;
@endphp
<!DOCTYPE html><html><head><meta charset="utf-8"><title>Quotation {{ $quotation->quote_number }}</title>@include('pdfs.partials.styles')</head><body class="template-{{ $documentTemplate }}">
@php($documentTitle = 'QUOTATION') @php($documentNumber = $quotation->quote_number) @include('pdfs.partials.header')
<table class="info"><tr><td><div class="label">PREPARED FOR</div><strong>{{ $quotation->client->name }}</strong><br>{!! nl2br(e($clientAddress)) !!}<br>{{ $clientEmail }} · {{ $quotation->client->phone ?: 'No phone' }}<br><strong>TIN:</strong> {{ $quotation->client->tin_number ?: 'Not provided' }}<br><strong>{{ $quotation->client->id_type ?: 'ID' }}:</strong> {{ $quotation->client->id_number ?: 'Not provided' }}<br><strong>SST:</strong> {{ $quotation->client->sst_registration_number ?: 'Not registered' }}</td><td><div class="label">DOCUMENT DETAILS</div><strong>Issue:</strong> {{ $quotation->date->format('d M Y') }}<br><strong>Valid until:</strong> {{ $quotation->expiry_date?->format('d M Y') ?? 'No expiry' }}<br><strong>Currency:</strong> {{ $settings['currency'] ?? 'MYR' }}<br><span class="badge partial">{{ strtoupper(str_replace('_', ' ', $quotation->status)) }}</span></td></tr></table>
<table class="items"><thead><tr><th>#</th><th>Item / Description</th><th class="num">Qty</th><th class="num">Unit Price</th><th class="num">Amount</th></tr></thead><tbody>@foreach($quotation->items as $item)<tr><td>{{ $loop->iteration }}</td><td><strong>{{ $item->item_name }}</strong>@if($item->description)<div class="muted document-rich-text">{!! $item->description !!}</div>@endif</td><td class="num">{{ $item->quantity }}</td><td class="num">RM {{ number_format($item->price, 2) }}</td><td class="num">RM {{ number_format($item->total, 2) }}</td></tr>@endforeach</tbody></table>
<table class="summary"><tr><td>Subtotal</td><td>RM {{ number_format($quotation->sub_total, 2) }}</td></tr><tr><td>Discount{{ $quotation->discount_type === 'percentage' ? ' ('.number_format($quotation->discount_value, 2).'%)' : '' }}</td><td>- RM {{ number_format($quotation->discount_amount, 2) }}</td></tr><tr><td>{{ Str::title(str_replace('_',' ', $quotation->tax_type ?: 'No tax')) }} ({{ number_format($quotation->tax_rate, 2) }}%)</td><td>RM {{ number_format($quotation->tax_amount, 2) }}</td></tr><tr class="grand"><td>Grand Total</td><td>RM {{ number_format($quotation->total_amount, 2) }}</td></tr></table><div class="clear"></div>
<div class="two"><div><div class="label">TERMS</div><p>{!! nl2br(e($settings['payment_terms'] ?? 'Prices are valid until the expiry date shown above.')) !!}</p></div><div><div class="label">E-INVOICE READY FIELDS</div><p>Document type: Quotation<br>Supplier registration: {{ $settings['company_registration_number'] ?? '—' }}<br>Supplier tax ID: {{ $settings['tax_registration_number'] ?? '—' }}<br>Buyer TIN: {{ $quotation->client->tin_number ?: '—' }}<br>Buyer ID: {{ $quotation->client->id_type ?: '—' }} {{ $quotation->client->id_number ?: '' }}<br>Tax category: {{ $quotation->tax_type ?: 'none' }}</p></div></div>
<div class="footer">{!! nl2br(e($settings['invoice_footer_note'] ?? 'Thank you for the opportunity to quote.')) !!}<br><span>Prepared by {{ $quotation->employee?->name }} · {{ now()->format('d M Y H:i') }}</span></div>
</body></html>
